/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.Timer;
import user.User;

/**
 *
 * @author Erasyl
 */
public class ProgressBar extends javax.swing.JFrame {

    /**
     * Creates new form ProgressBar
     * 
     */
    
    private Timer t = null;
    private int count = 0;
    User user;
    
    public ProgressBar(User user) {
        initComponents();
        convertWindow();
        this.user = user;
        loadProgressBar();
    }
    
    private void convertWindow() {
        setSize(510, 320);
        setResizable(false);
        setTitle("Smart Security");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
    }
    
    private void loadProgressBar() {
//        
        t = new Timer(100, (ActionEvent e) -> {
            count++;
            jLabelProgresPercent.setText(count + "%");
            jProgressBar1.setValue(count);
            if (jProgressBar1.getValue() < 100) {
                jProgressBar1.setValue(jProgressBar1.getValue() + 1);
            }
            if (count == 1) {
                jLabelProgessStep.setText("Подготовка..");
            }
            if (count == 10) {
                jLabelProgessStep.setText("Проверка данных..");
            }
            if (count == 50) {
                jLabelProgessStep.setText("Получения информаций..");
            }
            if (count == 90) {
                jLabelProgessStep.setText("Проверка состояний сайтов..");
            }
            if (count == 100) {
                validateAndLogin();
            }
        });
        t.start();
    }
    
    private void validateAndLogin() {
        try {
            URL url = new URL("http://diplom.loc/urlVerification.php?login=1&email="+ user.getEmail() +"&password=" + user.getPass());
            URLConnection yc = url.openConnection();
            try (BufferedReader in = new BufferedReader( new InputStreamReader(yc.getInputStream()))) {
                String inputLine;
                if ((inputLine = in.readLine()) != null) {
                    if (inputLine.length() > 2 && inputLine.substring(0, 2).equals("ok")) {
                        String [] userData = inputLine.split("[&]");
                        user.setId(userData[1]);
                        user.setName(userData[2]);
                        user.setTelegram(userData[3]);
                        user.setPhone(userData[4]);
                        System.out.println("test");
                        TimerTest timerTest = new TimerTest(user);
                        timerTest.setVisible(true);
                        close();
                    } 
                }
            }
        } catch (IOException e) {
        }
    }
    
    public void close() {
        WindowEvent windowEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabelProgessStep = new javax.swing.JLabel();
        jLabelProgresPercent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 280, 520, 10);

        jLabelProgessStep.setForeground(new java.awt.Color(255, 102, 51));
        getContentPane().add(jLabelProgessStep);
        jLabelProgessStep.setBounds(170, 260, 315, 14);

        jLabelProgresPercent.setForeground(new java.awt.Color(255, 102, 51));
        getContentPane().add(jLabelProgresPercent);
        jLabelProgresPercent.setBounds(130, 260, 31, 14);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 255));
        jLabel3.setText("Smart Security");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 20, 293, 37);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Этот SEO-инструмент, используемый непосредственно из вашего браузера, ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 440, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("служит для массовой проверки ответных кодов HTTP, полученных с веб-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 440, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("серверов (код статуса HTTP и код ответа). Это полезно как для тех, кто ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 440, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("практикует SEO, и хочет таким образом фильтровать список веб-страниц по ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 130, 440, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("кодам ответов, так и для веб-мастеров, которые выполняют обычную ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 150, 440, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("рутинную проверку состояния сайта. Также - вы с его помощью можете ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 170, 440, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("проверить конкурентные сайты или использовать его для «построения ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 190, 440, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("нерабочих ссылок»");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 210, 417, 14);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erasyl\\Pictures\\2.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 520, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProgessStep;
    private javax.swing.JLabel jLabelProgresPercent;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
