/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import user.User;

/**
 *
 * @author Erasyl
 */
public class TimerTest extends javax.swing.JFrame {

    User user;
    private ArrayList<String> okSites, errSites;
    private javax.swing.Timer t = null;
    private int count = 0;
    private int clickedTable = 0; 
    private String urlForRemove = "";
    /**
     * Creates new form TimerTest
     * @param user
     */
    
    public TimerTest(User user) {
        initComponents();
        convertWindow();
        this.user = user;
        jLabelUserName.setText(user.getName());
        jLabelUserEmail.setText(user.getEmail());
        jLabelPhone.setText(user.getPhone());
        jLabelUserTelegram.setText(user.getTelegram());
        getSites();
    }
    
    private void loadProgressBar() {
//        
        t = new javax.swing.Timer(100, (ActionEvent e) -> {
            count++;
            jLabelProgresPercent.setText(count + "%");
            jProgressBar1.setValue(count);
            if (jProgressBar1.getValue() < 100) {
                jProgressBar1.setValue(jProgressBar1.getValue() + 1);
            }
            if (count == 1) {
                jLabelProgessStep.setText("Подготовка..");
            }
            if (count == 10) {
                jLabelProgessStep.setText("Проверка данных..");
            }
            if (count == 20) {
                jLabelProgessStep.setText("Проверка состояний сайтов..");
            }
            if (count == 99) {
                getSites();
                count = 0;
                jLabelProgessStep.setText("");
                jLabelProgresPercent.setText("");
                jProgressBar1.setValue(count);
                t.stop();
            }
        });
        t.start();
    }
    // 
    private void convertWindow() {
        setSize(1100, 650);
        setResizable(false);
        setTitle("Smart Security");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBoxInterval = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUrl = new javax.swing.JTextField();
        jButtonAddSite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserEmail = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelUserTelegram = new javax.swing.JLabel();
        jTabbedPaneSites = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOK = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableErrs = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQueue = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonRemove = new javax.swing.JButton();
        jTextFieldChange = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabelProgresPercent = new javax.swing.JLabel();
        jLabelProgessStep = new javax.swing.JLabel();
        jToggleButtonCheckAllSites = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setForeground(new java.awt.Color(255, 102, 51));
        jButton1.setText("Начать проверку");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Выйти");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jComboBoxInterval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 мин", "20 мин", "30 мин", "1 ч", "2 ч", "5 ч" }));
        jComboBoxInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIntervalActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Добавить сайт на проверку")));

        jTextFieldUrl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });

        jButtonAddSite.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonAddSite.setText("Добавить");
        jButtonAddSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSiteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setText("Введите URL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddSite, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Сервис");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Справка");

        jButton6.setText("Вид");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Пользователь"));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText("Имя:");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setText("Телефон:");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setText("E-mail:");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setText("Телеграм:");

        jLabelUserName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelUserName.setText("name");

        jLabelUserEmail.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelUserEmail.setText("e-mail");

        jLabelPhone.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelPhone.setText("phone");

        jLabelUserTelegram.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelUserTelegram.setText("telegram");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserTelegram, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelUserEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelUserTelegram))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTableOK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№", "URL", "Status", "Server"
            }
        ));
        jTableOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOKMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableOK);

        jTabbedPaneSites.addTab("Рабочие", jScrollPane2);

        jTableErrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№", "URL"
            }
        ));
        jTableErrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableErrsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableErrs);

        jTabbedPaneSites.addTab("Не рабочие", jScrollPane1);

        jTableQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№", "URL", "Время добавления"
            }
        ));
        jScrollPane3.setViewportView(jTableQueue);

        jTabbedPaneSites.addTab("В очереди", jScrollPane3);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonRemove.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonRemove.setText("Удалить");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton3.setText("Открыть сайт");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldChange)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 461, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextFieldChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButtonRemove))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jToggleButtonCheckAllSites.setText("Проверить все сайты");
        jToggleButtonCheckAllSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCheckAllSitesActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Интервал проверки:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jToggleButtonCheckAllSites, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPaneSites, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(993, 993, 993)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabelProgresPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelProgessStep, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jToggleButtonCheckAllSites)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jComboBoxInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jTabbedPaneSites, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jToggleButton1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProgresPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProgessStep, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Timer timer = new Timer();
    DefaultListModel dlm = new DefaultListModel();
    int indx = 0;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // 5 10 20 30 1 2 5
        int interval = 5;
        int selInd = jComboBoxInterval.getSelectedIndex();
        switch (selInd) {
            case 1:
                interval = 10;
                break;
            case 2:
                interval = 20;
                break;
            case 3:
                interval = 30;
                break;
            case 4:
                interval = 60;
                break;
            case 5:
                interval = 120;
                break;
            case 6:
                interval = 300;
                break;
            default:
                break;
        }
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                getSites();
            }
          },  interval*1000, 2*1000);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void getSites() {
        try {
            URL url = new URL("http://diplom.loc/urlVerification.php?info-sites=" + user.getId());
            URLConnection yc = url.openConnection();
            try (BufferedReader in = new BufferedReader( new InputStreamReader(yc.getInputStream()))) {
                String inputLine;
                String allSites = "";
                while ((inputLine = in.readLine()) != null) {
                    allSites = allSites + inputLine;
                }
                int afterErr = allSites.indexOf("Q#Q#Q");
                allSites = allSites.substring(afterErr + 5);
                System.out.println(allSites);
                String diffSites[] = allSites.split("[*]");
                okSites = convertToList(diffSites[0]);
                errSites = convertToList(diffSites[1]);
                
                showErrSitesInTable();
                showOKSitesInTable();
            }
        } catch (IOException e) {
        }
    }
    
    private void showOKSitesInTable() {
        DefaultTableModel model = (DefaultTableModel) jTableOK.getModel();
        model.getDataVector().removeAllElements();
        Object[] row = new Object[4];
        for (int i = 0; i < okSites.size(); ++i) {
            String info[] = okSites.get(i).split("@");
            row[0] = i + 1;
            row[1] = info[0];
            if (info.length > 1) row[2] = info[1];
            if (info.length > 2) row[3] = info[2].split("[:]")[1];
            model.addRow(row);
        }
    }
    
    private void showErrSitesInTable() {
        DefaultTableModel model = (DefaultTableModel) jTableErrs.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < errSites.size(); ++i) {
            row[0] = i + 1;
            row[1] = errSites.get(i);
            model.addRow(row);
        }
    }
    
    private void addQueueSite(String url) {
        DefaultTableModel model = (DefaultTableModel) jTableQueue.getModel();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        model.addRow(new Object[]{model.getRowCount() + 1, url, sdf.format(cal.getTime())});
    }
    
    private ArrayList<String> convertToList(String str) {
        ArrayList<String> list = new ArrayList<>(Arrays.asList(str.split("[#]")));
        return list;
    }
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView browserView = new BrowserView(browser);

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.add(browserView, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL(jTextFieldChange.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAddSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSiteActionPerformed
        // TODO add your handling code here:
        try {
            String site = jTextFieldUrl.getText().trim();
            jTextFieldUrl.setText("");
            URL url = new URL("http://diplom.loc/urlVerification.php?insert-site=" + site + "&user_id=" + user.getId());
            URLConnection yc = url.openConnection();
            try (BufferedReader in = new BufferedReader( new InputStreamReader(yc.getInputStream()))) {
                String inputLine;
                String res = "";
                while ((inputLine = in.readLine()) != null) {
                    res = res + inputLine;
                }
                System.out.println(res);
                JOptionPane.showMessageDialog(null, res, "Отправлен", JOptionPane.INFORMATION_MESSAGE);
                addQueueSite(site);
            }
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButtonAddSiteActionPerformed

    private void jTableErrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableErrsMouseClicked
        int ind = jTableErrs.getSelectedRow();
        TableModel model = jTableErrs.getModel();
        jTextFieldChange.setText(model.getValueAt(ind, 1).toString());
        clickedTable = 2;
    }//GEN-LAST:event_jTableErrsMouseClicked

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed

    private void jTableOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOKMouseClicked
        int ind = jTableOK.getSelectedRow();
        TableModel model = jTableOK.getModel();
        jTextFieldChange.setText(model.getValueAt(ind, 1).toString());
        clickedTable = 1;
    }//GEN-LAST:event_jTableOKMouseClicked

    private void jToggleButtonCheckAllSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCheckAllSitesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableQueue.getModel();
        model.setRowCount(0);
        loadProgressBar();
    }//GEN-LAST:event_jToggleButtonCheckAllSitesActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
        System.out.println("1");
        switch (clickedTable) {
            case 1:
                {
                    System.out.println("2");
                    int ind = jTableOK.getSelectedRow();
                    removeFromDataBase(jTextFieldChange.getText());
                    ((DefaultTableModel)jTableOK.getModel()).removeRow(ind);
                    break;
                }
            case 2:
                {
                    int ind = jTableErrs.getSelectedRow();
                    removeFromDataBase(jTextFieldUrl.getText());
                    System.out.println(jTextFieldUrl.getText());
                    ((DefaultTableModel)jTableErrs.getModel()).removeRow(ind);
                    break;
                }
            default:
                JOptionPane.showMessageDialog(null, "Выберите элемент из таблицы", "Элемент не выбран", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
        clickedTable = 0;
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void removeFromDataBase(String siteUrl) {
        try {
            String myUrl = "http://diplom.loc/urlVerification.php?delete-site=" + siteUrl;
            System.out.println(myUrl);
            URL url = new URL(myUrl);
            URLConnection yc = url.openConnection();
            try (BufferedReader in = new BufferedReader( new InputStreamReader(yc.getInputStream()))) {
                String inputLine;
                String res = "";
                while ((inputLine = in.readLine()) != null) {
                    res = res + inputLine;
                }
                System.out.println(res);
                jTextFieldChange.setText("");
            }
        } catch (IOException e) {
        }
    }
    
    private void jComboBoxIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIntervalActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAddSite;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JComboBox<String> jComboBoxInterval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelProgessStep;
    private javax.swing.JLabel jLabelProgresPercent;
    private javax.swing.JLabel jLabelUserEmail;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserTelegram;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneSites;
    private javax.swing.JTable jTableErrs;
    private javax.swing.JTable jTableOK;
    private javax.swing.JTable jTableQueue;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldUrl;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonCheckAllSites;
    // End of variables declaration//GEN-END:variables
}

/*

1 url
2 status
3 server
4 ошибка

*/